# -- granulate base 64 id
b64ClientId: ""
# -- plain text name
clientName: ""
# -- plain text service name
serviceName: ""
# -- plain text namespace we deploy the gmaestro
namespace: ""
# -- Image tags should not be changed unless explicitly needed
maestroImageTag: latest

# -- labels are inserted into the maestro agent deployment
customLabel:
  labelA: ""

# -- node selector is used granulate maestro agent deployment
nodeSelector:
  firstKey: ""

secrets:
  grafanaMetricsAuthKey: longAuthKeyHere
